services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: app:${APP_VERSION:-latest}
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      APP_HOST: 0.0.0.0
      APP_DB_HOST: app-db
      APP_DB_PORT: 5432
      APP_DB_USER: app
      APP_DB_PASS: app
      APP_DB_BASE: app
      APP_REDIS_HOST: app-redis

  db:
    image: postgres:17
    hostname: app-db
    environment:
      POSTGRES_PASSWORD: "app"
      POSTGRES_USER: "app"
      POSTGRES_DB: "app"
    volumes:
      - app-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U app
      interval: 2s
      timeout: 3s
      retries: 40
    
  migrator:
    image: app:${APP_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      APP_DB_HOST: app-db
      APP_DB_PORT: 5432
      APP_DB_USER: app
      APP_DB_PASS: app
      APP_DB_BASE: app
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:8
    hostname: "app-redis"
    restart: always
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

  celery-worker:
    <<: *main_app
    restart: always
    command: ["/bin/bash", "/app/src/scripts/celery_worker.sh"]
    environment:
      APP_DB_HOST: app-db
      APP_DB_PORT: 5432
      APP_DB_USER: app
      APP_DB_PASS: app
      APP_DB_BASE: app
      APP_REDIS_HOST: app-redis
      APP_CELERY_BROKER_URL: "redis://app-redis:6379/0"
      APP_CELERY_BACKEND_URL: "redis://app-redis:6379/1"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery-beat:
    <<: *main_app
    restart: always
    command: ["/bin/bash", "/app/src/scripts/celery_beat.sh"]
    environment:
      APP_DB_HOST: app-db
      APP_DB_PORT: 5432
      APP_DB_USER: app
      APP_DB_PASS: app
      APP_DB_BASE: app
      APP_REDIS_HOST: app-redis
      APP_CELERY_BROKER_URL: "redis://app-redis:6379/0"
      APP_CELERY_BACKEND_URL: "redis://app-redis:6379/1"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy



volumes:
  app-db-data:
    name: app-db-data
